apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lib-helm-app.fullname" . }}
data:
{{- range $key, $val := .Values.configmapToEnv }}
  {{ $key }}: {{ $val | quote }}
{{- end}}
{{- range $configmapToFile := .Values.configmapToFile }}
  {{ $configmapToFile.nameFile }}: |
    {{- $configmapToFile.data | nindent 4 -}}
{{- end}}
