{{- if .Values.route.enabled -}}
  {{- range .Values.route.hosts }}
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  {{- if .host }}
  name: {{ include "lib-helm-app.fullname" $ }}-{{ .host }}
  {{- else }}
  name: {{ include "lib-helm-app.fullname" $ }}
  {{- end }}
  labels:
    {{- include "lib-helm-app.labels" $ | nindent 4 }}
    {{- range $key, $val := $.Values.commonlabels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
    {{- range $key, $val := $.Values.routelabels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
spec:
  {{- if .host }} 
  host: {{ .host }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "lib-helm-app.fullname" $ }}
    weight: {{ .weight }}
  port:
    targetPort: {{ .targetPort }}
  tls:
    termination: {{ .tls.termination }}
    {{- if .tls.insecureEdgeTerminationPolicy }}
    insecureEdgeTerminationPolicy: {{ .tls.insecureEdgeTerminationPolicy }}
    {{- end }}
  wildcardPolicy: {{ .wildcardPolicy }}
  {{- end }}
{{- end }}
