{{- if .Values.sealedsecrets.enabled -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "lib-helm-app.fullname" . }}
spec:
  encryptedData:
  {{- range $key, $val := .Values.sealedsecrets.data }}
    {{ $key }}: {{ $val | quote }}
  {{- end}}
  {{- if .Values.sealedsecretsToFilesEnabled }}{{- range $sealedsecretsToFiles := .Values.sealedsecretsToFiles }}
    {{ $sealedsecretsToFiles.secretKey }}: {{ $sealedsecretsToFiles.data | quote }}
  {{- end}}{{- end }}
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: {{ include "lib-helm-app.fullname" . }}
      namespace: {{ .Release.Namespace }}
{{- end }}
