{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lib-helm-app.serviceAccountName" . }}
  labels:
    {{- include "lib-helm-app.labels" . | nindent 4 }}
    {{- range $key, $val := .Values.commonlabels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
    {{- range $key, $val := .Values.ingresslabels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}

  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "lib-helm-app.serviceAccountName" . }}-view
  labels:
    {{- include "lib-helm-app.labels" . | nindent 4 }}
    {{- range $key, $val := .Values.commonlabels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
    {{- range $key, $val := .Values.ingresslabels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
subjects:
- kind: ServiceAccount
  name: {{ include "lib-helm-app.serviceAccountName" . }}    
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
{{- end }}